apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: tcp-monitor-daemon
  labels:
    monitor: tcp

spec:
  selector:
    matchLabels:
      monitor: tcp

  template:
    metadata:
      name: tcp-monitor-daemon
      labels:
        monitor: tcp
      annotations:
        prometheus.io/job: tcp-monitor
        prometheus.io/path: /metrics

    spec:
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule

        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule

      containers:
        - name: tcp-monitor
          image: alisalemmi/tcp-monitor:latest

          ports:
            - name: prom-metrics
              protocol: TCP
              containerPort: 3000
              hostPort: 3000

          volumeMounts:
            - name: proc-net
              mountPath: /host/net

      volumes:
        - name: proc-net
          hostPath:
            path: /proc/net

      hostNetwork: true
